image: archlinux
packages:
  - systemd
  - libconfig
  - libcups
  - ncurses
  - libarchive
  - glibc
  - libnotify
  - cmake
  - bash-completion
sources:
  - https://github.com/FedeDP/ncursesFM
tasks:
  - prepare: |
      cd ncursesFM
      mkdir build
      cd build
      cmake -DENABLE_CUPS=true -DENABLE_NOTIFY=true ..
  - build: |
      cd ncursesFM/build
      make
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
