sudo: required

notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: never
    on_failure: always

arch:
    packages:
        - systemd
        - libconfig
        - glibc
        - libarchive
        - ncurses
        - libcups
        - libx11
        - openssl
    script: make

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

