sudo: required

notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: never
    on_failure: always

language: c

compiler:
  - gcc
  - clang

arch:
    packages:
        - systemd
        - libconfig
        - glibc
        - libarchive
        - ncurses
        - libcups
        - libx11
        - bash-completion
    script:
        - "echo $CC"
        - make
        - make DISABLE_LIBSYSTEMD=1
        - make DISABLE_LIBCUPS=1
        - make DISABLE_LIBCONFIG=1
        - make DISABLE_LIBX11=1
        - make debug

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

