sudo: required
dist: trusty

language: c

compiler: gcc

script: make

notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      - libncursesw5-dev
      - libarchive-dev
      - pkg-config
      - libcups2-dev
      - libudev-dev
      - libconfig-dev
      - libx11-dev
      - libsystemd-login-dev
      - libsystemd-daemon-dev
      - libssl-dev
